{"id":38785901,"login":"zrlurb","contributions":{"total":1,"by_kind":{"commit":0,"issue":1,"pull_request":0}},"repositories":["open-quantum-safe/liboqs-python"],"years":[2023],"first_contribution":{"kind":"issue","owner":"open-quantum-safe","repository":"liboqs-python","sha":null,"number":64,"title":"PYPI  pip get an SSLError","ts":1687266876}}